/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "count": number;
        "updateCount": (value: number) => Promise<void>;
    }
    interface MyComponentButton {
        "incrementValues": number[];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyComponentButtonElement extends Components.MyComponentButton, HTMLStencilElement {
    }
    var HTMLMyComponentButtonElement: {
        prototype: HTMLMyComponentButtonElement;
        new (): HTMLMyComponentButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-component-button": HTMLMyComponentButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "count"?: number;
    }
    interface MyComponentButton {
        "incrementValues"?: number[];
        "onIncrement"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-component-button": MyComponentButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-component-button": LocalJSX.MyComponentButton & JSXBase.HTMLAttributes<HTMLMyComponentButtonElement>;
        }
    }
}
